"""conversation state: clarification loop

Revision ID: d44e23a78323
Revises: 2398165680b3
Create Date: 2026-09-14 12:36:21.259302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd44e23a78323'
down_revision: Union[str, None] = '2398165680b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate doesn't detect Postgres enum value additions -- added
    # by hand. Safe inside this transaction on PG12+ as long as nothing
    # in the same migration inserts a row using the new value, which
    # nothing here does.
    op.execute("ALTER TYPE processing_run_state ADD VALUE IF NOT EXISTS 'AWAITING_CLARIFICATION'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_runs",
        sa.Column("clarification_rounds", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "processing_runs", sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_runs", "messages")
    op.drop_column("processing_runs", "clarification_rounds")
    # ### end Alembic commands ###
    # Postgres has no ALTER TYPE ... DROP VALUE -- removing the
    # AWAITING_CLARIFICATION enum label on downgrade isn't supported
    # without rebuilding the type. Left in place; harmless if unused.
