"""candidate intents on ai invocation

Revision ID: 39f20ee2ac48
Revises: d44e23a78323
Create Date: 2026-09-14 12:57:42.789727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39f20ee2ac48'
down_revision: Union[str, None] = 'd44e23a78323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_invocations', sa.Column('candidate_intents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_invocations', 'candidate_intents')
    # ### end Alembic commands ###
