"""calendar sync state on appointment

Revision ID: 2ff7085132cd
Revises: 39f20ee2ac48
Create Date: 2026-09-15 07:54:53.255808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff7085132cd'
down_revision: Union[str, None] = '39f20ee2ac48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic doesn't auto-emit CREATE TYPE for a bare ALTER TABLE ADD
    # COLUMN outside full table creation -- has to be created explicitly
    # first (unlike Postgres enum *value* additions, which used
    # op.execute ALTER TYPE in an earlier migration; this is a brand new
    # type, not a new value on an existing one).
    calendar_sync_status = sa.Enum(
        "PENDING", "SYNCED", "FAILED", name="calendar_sync_status"
    )
    calendar_sync_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments", sa.Column("calendar_event_id", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "appointments",
        sa.Column(
            "calendar_sync_status",
            calendar_sync_status,
            nullable=False,
            server_default="PENDING",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointments", "calendar_sync_status")
    op.drop_column("appointments", "calendar_event_id")
    # ### end Alembic commands ###
    sa.Enum(name="calendar_sync_status").drop(op.get_bind(), checkfirst=True)
