"""background jobs: reminders, no-show recovery, scheduled jobs

Revision ID: 345f07f025e7
Revises: 2ff7085132cd
Create Date: 2026-09-15 09:55:50.835728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '345f07f025e7'
down_revision: Union[str, None] = '2ff7085132cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # processing_run_kind is used in a bare ADD COLUMN on an existing
    # table below -- same Alembic gotcha as calendar_sync_status hit
    # earlier: has to be created explicitly first. scheduled_job_type and
    # scheduled_job_status don't need this -- they're created as part of
    # a fresh CREATE TABLE, which SQLAlchemy handles automatically.
    processing_run_kind = sa.Enum("CUSTOMER_INITIATED", "RECOVERY", name="processing_run_kind")
    processing_run_kind.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('SEND_REMINDER', name='scheduled_job_type'), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LOCKED', 'DONE', 'FAILED_RETRYABLE', name='scheduled_job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('rebooked_from_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'appointments', ['rebooked_from_id'], ['id'], ondelete='SET NULL')
    op.add_column(
        'businesses',
        sa.Column(
            'no_show_grace_period_minutes', sa.Integer(), nullable=False, server_default='15'
        ),
    )
    op.add_column(
        'businesses',
        sa.Column('reminder_lead_hours', sa.Integer(), nullable=False, server_default='24'),
    )
    op.add_column(
        'processing_runs',
        sa.Column(
            'kind',
            processing_run_kind,
            nullable=False,
            server_default='CUSTOMER_INITIATED',
        ),
    )
    op.add_column('processing_runs', sa.Column('recovery_of_appointment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'processing_runs', 'appointments', ['recovery_of_appointment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processing_runs', type_='foreignkey')
    op.drop_column('processing_runs', 'recovery_of_appointment_id')
    op.drop_column('processing_runs', 'kind')
    op.drop_column('businesses', 'reminder_lead_hours')
    op.drop_column('businesses', 'no_show_grace_period_minutes')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'rebooked_from_id')
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###
    sa.Enum(name="processing_run_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="scheduled_job_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="scheduled_job_status").drop(op.get_bind(), checkfirst=True)
