"""cancellation and rescheduling

Revision ID: 4a32a5fa325c
Revises: 345f07f025e7
Create Date: 2026-09-15 10:28:21.117085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a32a5fa325c'
down_revision: Union[str, None] = '345f07f025e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'businesses',
        sa.Column(
            'min_reschedule_notice_hours', sa.Integer(), nullable=False, server_default='24'
        ),
    )
    op.add_column('processing_runs', sa.Column('target_appointment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'processing_runs_target_appointment_id_fkey',
        'processing_runs',
        'appointments',
        ['target_appointment_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Named explicitly -- autogenerate's placeholder `None` name can't be
    # resolved back to the real constraint name at drop time.
    op.drop_constraint(
        'processing_runs_target_appointment_id_fkey', 'processing_runs', type_='foreignkey'
    )
    op.drop_column('processing_runs', 'target_appointment_id')
    op.drop_column('businesses', 'min_reschedule_notice_hours')
    # ### end Alembic commands ###
