"""business api key

Revision ID: 9d35e1f0199e
Revises: 4a32a5fa325c
Create Date: 2026-09-15 13:45:53.926194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d35e1f0199e'
down_revision: Union[str, None] = '4a32a5fa325c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'api_key_hash')
    # ### end Alembic commands ###
